name: Deployment Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
      - docs/**
      - "*.md"
      - .gitignore

jobs:

  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate staging build
        run: |
          echo "Deploying to STAGING environment"
          echo "Image: sakila-app:staging"

      - name: Simulated Docker build
        run: |
          echo "docker build -t sakila-app:staging ."
          echo "docker run sakila-app:staging"

      - name: Job Summary (STAGING)
        run: |
          echo "## 🚀 Staging Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "- Environment: staging" >> $GITHUB_STEP_SUMMARY
          echo "- Image: sakila-app:staging" >> $GITHUB_STEP_SUMMARY
          echo "- Status: SUCCESS" >> $GITHUB_STEP_SUMMARY

      - name: Notify staging
        run: echo "Slack notification: staging deployment successful"


  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate version tag
        run: echo "TAG=v$(date +'%Y.%m.%d')" >> $GITHUB_ENV

      - name: Production deployment
        run: |
          echo "Deploying to PRODUCTION"
          echo "Version: $TAG"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: Release ${{ env.TAG }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify production
        run: echo "Slack notification: production deployment successful"